# Generated by Django 2.2.4 on 2019-09-09 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('brief', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('app_package', models.CharField(max_length=200, verbose_name='Package')),
                ('app_id', models.CharField(max_length=50, null=True, unique=True, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Website')], max_length=200, verbose_name='Type')),
                ('server', models.BooleanField(default=1, help_text='Provide server account to this user', verbose_name='Server status')),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=1)),
                ('created_by', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(related_name='registration_features', to='apis.Feature')),
            ],
        ),
    ]
