# Generated by Django 2.2.4 on 2019-09-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_is_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
