name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "a)&jz+!czx-e^6!f_6av&z3&1rl84kk7_5c432j==-wkhp!x!@"
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make media, log folder
      run: |
        mkdir media
        cd media && mkdir logs
    - name: Run Tests
      run: |
        python manage.py test
